apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-app-dev-traefik
  namespace: outline-stack
  annotations:
    kubernetes.io/ingress.class: traefik-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: outline-dev-selfsigned
spec:
  ingressClassName: traefik-traefik
  rules:
    - host: outline.apps.deem.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: outline
                port:
                  number: 3000
  tls:
    - hosts:
        - outline.apps.deem.local
      secretName: outline-app-dev-tls
