apiVersion: v1
kind: Namespace
metadata:
  name: basier
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-env
  namespace: basier
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootPass123
  MYSQL_DATABASE: prestashop
  MYSQL_USER: pshop
  MYSQL_PASSWORD: pshopPass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: basier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: <your-storage-class>   # (optional) use cluster default if omitted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: basier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: mysql
          image: mysql:8.4
          args: ["--default-authentication-plugin=mysql_native_password"]
          envFrom:
            - secretRef:
                name: mysql-env
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: basier
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
  namespace: basier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - name: prestashop
          image: prestashop/prestashop:1.7.8.1
          env:
            - name: PS_INSTALL_AUTO
              value: "1"
            - name: DB_SERVER
              value: mysql
            - name: DB_NAME
              value: prestashop
            - name: DB_USER
              value: pshop
            - name: DB_PASSWORD
              value: pshopPass
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prestashop-data
              mountPath: /var/www/html
      volumes:
        - name: prestashop-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prestashop
  namespace: basier
spec:
  type: NodePort
  selector:
    app: prestashop
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080