---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql
  namespace: psql
  labels:
    app: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: postgres:14.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: demo
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              vaule: admin123
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: psql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: psql
          emptyDir: {}


