---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql
  namespace: psql
  labels:
    app: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: postgres:14.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: cman
            - name: POSTGRES_USER
              value: cman
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: psql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: psql
          emptyDir: {}


