---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: auth

  chart:
    spec:
      chart: ./manifests/dev/infra/keycloak
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
      reconcileStrategy: ChartVersion

  values:
    global:
      postgresql:
        auth:
          password: KeycloakDB@12345

    auth:
      adminUser: admin
      adminPassword: Admin@12345

    image:
      registry: docker.io
      repository: bitnamilegacy/keycloak
      tag: 26.3.3-debian-12-r0

    postgresql:
      enabled: true
      auth:
        username: bn_keycloak
        password: KeycloakDB@12345
        database: bitnami_keycloak
        postgresPassword: PostgresRoot@12345
      image:
        registry: docker.io
        repository: bitnamilegacy/postgresql
        tag: 17.6.0-debian-12-r0

    proxyHeaders: xforwarded
    httpEnabled: true
    ingress:
      enabled: true
      hostname: keycloak.deem.local
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/router.middlewares: auth-headers@kubernetescrd