apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong-release
  namespace: kong
spec:
  interval: 5m
  chart:
    spec:
      chart: kong
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kong-repo
        namespace: kong
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: kong-values
