---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1m
  install:
    createNamespace: true
  path: ./infrastructure
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
      verrsion: 70.7.0
  valuesFrom:
    - configMapKeyRef:
        name: kube-prometheus-stack
        key: values.yaml