---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  annotations: 
    vault.hashicorp.com/agent-inject: true
    vault.hashicorp.com/role: 'internal-app'
    vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/db/config'
resources:
  - demo1
  - demo2
  - prestashop
