apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: karpor
    # If the chart is local, use 'path' (relative to kustomization.yaml)
    # If remote, use 'repo', 'name', and 'version'
    path: ./karpor 
    releaseName: karpor-release
    valuesFile: ./karpor/values.yaml
