apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: karpor        # The name of the folder inside 'infra'
  chartHome: .        # Tells Kustomize to look in the current directory
  releaseName: karpor
  valuesFile: karpor/values.yaml
