---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: basier
  namespace: flux-system
spec:
  interval: 5s
  path: ./manifests/dev/basier/
  prune: true
  timeout: 1m0s
  wait: false
  sourceRef:
    kind: GitRepository
    name: basier
      #  targetNamespace: basier
