---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: basier
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    #/*
    # include deploy dir
    #!/deploy
    # exclude file extensions from deploy dir
    /deploy/**/*.md
    /deploy/**/*.txt 
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
