---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    spec:
      chart: grafana
      version: 8.5.6
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  releaseName: grafana
  targetNamespace: monitoring
  values:
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: standard
    replicas: 1
