apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin
  namespace: harbor
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: "Admin$@2025"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  url: https://helm.goharbor.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: "1.14.2" # You can update to the latest version if needed
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # harborAdminPassword: "Welcome@123" # Change this to a secure password
    existingSecretAdminPassword: harbor-admin
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
    persistence:
      enabled: true
      resourcePolicy: keep