---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 5s
  path: ./manifests/dev/harbor/v1/
  prune: true
  timeout: 1m0s
  wait: false
  namespace: harbor
  sourceRef:
    kind: GitRepository
    name: harbor
