---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
---
# clusters/dev/harbor/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor-system
spec:
  interval: 30m
  chart:
    spec:
      # <— this is the chart DIR path inside your Git repo
      chart: ./manifests/dev/harbor/v1/harbor
      sourceRef:
        kind: GitRepository
        name: harbor
        namespace: flux-system
      # When sourcing from GitRepository, version is ignored
      # (helm-controller builds the chart from the path)
      # ref: https://github.com/fluxcd/helm-controller/blob/main/docs/spec/v2beta1/helmreleases.md
  install:
    createNamespace: true
    # optional CRD policy example; Harbor doesn't ship CRDs
    # crds: Create
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    expose:
      type: ingress
      tls:
        enabled: false
      ingress:
        className: nginx
        hosts:
          core: harbor.minikube.local
    externalURL: "http://harbor.minikube.local"
    harborAdminPassword: "ChangeMe_Strong!"
---
# clusters/dev/harbor/kustomization.yaml  (points to the files above, NOT the chart)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 5s
  path: ./clusters/staging
  prune: true
  wait: false
  timeout: 1m0s
  sourceRef:
    kind: GitRepository
    name: harbor