apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  url: https://helm.goharbor.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: "1.14.2" # You can update to the latest version if needed
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    expose:
      type: ingress
      ingress:
        hosts:
          core: harbor.staging.example.com
          notary: notary.harbor.staging.example.com
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: harbor-tls
            hosts:
              - harbor.staging.example.com
              - notary.harbor.staging.example.com
    externalURL: https://harbor.staging.example.com
    harborAdminPassword: "Welcome@123" # Change this to a secure password
    persistence:
      enabled: true
      resourcePolicy: keep
      persistentVolumeClaim:
        registry:
          storageClass: "standard"
          accessMode: ReadWriteOnce
          size: 20Gi
        chartmuseum:  
          storageClass: "standard"
          accessMode: ReadWriteOnce
          size: 10Gi

    