---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hashicorp-vault
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "false"
    # fluxcd.io/health-check: "true"
spec:
  chart:
    spec:
      chart: ./manifests/dev/infra/vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  interval: 10s
  targetNamespace: hashicorp-vault
  values:
    ui: 
     enabled: true
     serviceType: "LoadBalancer"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp-vault
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.releases.hashicorp.com
  secretRef:
    name: hashicorp-vault-helm-repo-creds
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: Secret
metadata:
  name: hashicorp-vault-helm-repo-creds
  namespace: flux-system
type: Opaque
data:
  username: dmF1bHQK
  password: dmF1bHQxMjMK
