---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/health-check: "true"
spec:
  chart:
    spec:
      chart: ./manifests/dev/monitoring/kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: monitoring
  interval: 10s
  targetNamespace: monitoring
  values:
    prometheus:
      prometheusSpec:
        storageClassName: standard
    grafana:
      adminPassword: admin
      adminUser: admin
      service:
        enabled: true
        type: ClusterIP
      replicas: 3