---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./manifests/dev/monitoring/kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra
  interval: 10s
  targetNamespace: monitoring
  values:
    prometheus:
      prometheusSpec:
        retention: 10d
        retentionSize: 100Gi
        storageClassName: standard
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
        serviceMonitorSelector:
          matchLabels:
            app: kube-prometheus-stack-prometheus-node-exporter
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      adminPassword: admin
      adminUser: admin
      service:
        enabled: true
        type: ClusterIP
      replicas: 3
      persistentVolume:
        enabled: true
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        size: 10Gi