---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/health-check: "true"
spec:
  chart:
    spec:
      chart: ./manifests/dev/monitoring/kong
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  interval: 10s
  targetNamespace: kong
  values:
      service:
        enabled: true
        type: ClusterIP
