---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hashicorp-vault
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault
      version: "0.27.0" # set desired version
      sourceRef:
        kind: HelmRepository
        name: hashicorp-vault
        namespace: flux-system
  interval: 10s
  targetNamespace: hashicorp-vault
  values:
    ui:
      enabled: true
    replicas: 1
    
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp-vault
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: v1
kind: Namespace
metadata:
  name: hashicorp-vault
  labels: 
    name: hashicorp-vault
