---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/health-check: "true"
spec:
  chart:
    spec:
      chart: ./manifests/dev/monitoring/kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  interval: 10s
  targetNamespace: monitoring
  values:
    prometheus:
      volumeClaimTemplate:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    grafana:
      adminPassword: admin
      adminUser: admin
      service:
        enabled: true
        type: ClusterIP
      replicas: 3
      persistence:
        enabled: true
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        size: 10Gi