---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
---
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ../../manifests/dev/monitoring/infrastructure/
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kube-prometheus-stack
  interval: 10s
  targetNamespace: monitoring