---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hashicorp-vault
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/health-check: "true"
spec:
  chart:
    spec:
      chart: ./manifests/dev/infra/vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  interval: 10s
  targetNamespace: hashicorp-vault
  values:
    ui: 
     enabled: true
     serviceType: "LoadBalancer"
