kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.7.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  interval: 1m0s
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    createNamespace: false
  targetNamespace: monitoring
  values:
    grafana:
      service:
        type: ClusterIP
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yml

