---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/health-check: "true"
spec:
  chart:
    spec:
      chart: ./manifests/dev/infra/minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  interval: 10s
  targetNamespace: minio
