---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: minio-latets
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: minio-latest
  policy:
    semver:
      range: main-{{.Values.minio.version}}
  interval: 10s
    
