---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 30s
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kong
      version: 2.48.0
  install:
    crds: Create
  interval: 1m0s
  releaseName: kong
  upgrade:
    crds: CreateReplace
