---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./manifests/dev/infra/
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra-hr
  interval: 10s
