---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 30s
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: kong
        version: 0.19.0
  interval: 1m0s
  releaseName: kong
  targetNamespace: kong
