---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-hr
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./manifests/dev/infra/
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: infra-hr
  interval: 10s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: basier
  namespace: flux-system
spec:
  interval: 5s
  path: ./manifests/dev/infra
  prune: true
  timeout: 1m0s
  wait: false
  sourceRef:
    kind: GitRepository
    name: infra-hr
      #  targetNamespace: basier
