---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jenkins
  interval: 10s
  targetNamespace: monitoring
  values:
    controller:
      JCasC:
        securityRealm: |-
          local:
            allowsSignup: false
            enableCaptcha: false
            users:
            - id: "${chart-admin-username}"
              name: "Jenkins Admin"
              password: "${chart-admin-password}"
        authorizationStrategy: |-
          loggedInUsersCanDoAnything:
            allowAnonymousRead: false
