---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 24.5.8
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
