---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keycloak
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keycloak
  interval: 10s
  releaseName: keycloak
  targetNamespace: keyclaok
  values: 
    replicaCount: 1
    keycloak:
      username: admin
      password: admin