# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: minio
#   namespace: flux-system
# spec:
#   url: https://charts.min.io/
#   interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: minio
  chart:
    spec:
      chart: ./manifests/dev/infra/minio
      reconcileStrategy: ChartVersion  # Replace with the desired chart version or use a variable
      sourceRef:
        kind: GitRepository
        name: minio
        namespace: flux-system
  values:
    mode: standalone           # Ensures a single instance
    replicas: 1                # Only one pod
    rootUser: minioadmin       # Username for MinIO UI/API
    rootPassword: minioadmin   # Password for MinIO UI/API
    persistence:
      enabled: true            # Enable persistent storage
      size: 10Gi               # Size of the persistent volume
      storageClass: "standard" # Adjust based on your cluster's storage class
---
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation