---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  url: https://charts.min.io/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: minio
  suspend: false
  chart:
    spec:
      chart: minio
      version: "8.0.10" # Use the latest stable version if needed
      #reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    mode: standalone           # Ensures a single instance
    replicas: 1                # Only one pod
    rootUser: minioadmin       # Username for MinIO UI/API
    rootPassword: minioadmin   # Password for MinIO UI/API
    persistence:
      enabled: true
      size: 10Gi
      storageClass: standard
    service:
      type: NodePort
      nodePort: 30007
      port: 9000
    consoleService:
      type: NodePort
      nodePort: 30008
      port: 9001
    resources:
      requests:
        memory: "2Gi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "200m"
        