---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./manifests/dev/infra/minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
        # kind: HelmRepository
        # name: prometheus-community
  interval: 10s
  targetNamespace: minio
  values:
    accessKey: minioadmin
    secretKey: minioadmin
    persistence:
      enabled: true
      size: 10Gi
      storageClass: standard
    service:
      type: NodePort
      nodePort: 30007
      port: 9000
    console:
      type: NodePort
      nodePort: 30008
      port: 9001
    model: standalone