apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/dev/monitoring/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

