---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: outline
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: basier
  namespace: flux-system
spec:
  #  commonMetadata:
    #    labels:
      #      environment: dev
  interval: 10s
  path: ./manifests/dev/basier/
  prune: true
  timeout: 1m0s
  wait: false
  sourceRef:
    kind: GitRepository
    name: basier

