---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./manifests/dev/basier/outline
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: outline
  interval: 10s
  install:
    createNamespace: true
  targetNamespace: outline
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: outline
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
