apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-ingress
  namespace: outline
  annotations:
    kubernetes.io/ingress.class: traefik
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: grafana-dev-selfsigned
spec:
  ingressClassName: traefik
  rules:
    - host: outline.deem.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-kube-prometheus-stack-grafana
                port:
                  number: 80
  tls:
    - hosts:
        - grafana-dev.local
      secretName: grafana-dev-tls
