apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-dev
  namespace: outline
  annotations:
    kubernetes.io/ingress.class: traefik
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: outline-dev-selfsigned
spec:
  ingressClassName: traefik
  rules:
    - host: outline-dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: outline
                port:
                  number: 3000
  tls:
    - hosts:
        - outline-dev.local
      secretName: outline-dev-tls
