---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: outline
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shahid430/flux-automation
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: outline
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: manifests/dev/basier/outline
      sourceRef:
        kind: GitRepository
        name: outline
        namespace: flux-system
  values:
    redis:
      enabled: true
      auth:
        enabled: true
        password: "P@ssw0rd123"
    extraEnvVars:
      - name: DATABASE_URL
        value: "postgres://devops:P@ssw0rd123@outline-postgresql:5432/outline"