apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: basier
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/dev/basier/petclinic
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

