---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-postgres-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pgp-exporter
  interval: 10s
  releaseName: pgp-exporter
  targetNamespace: monitoring
