---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/dev/infra/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
