---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zabbix
  namespace: flux-system
spec:
  chart:
    spec:
      chart: zabbix
      version: "1.2.7"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m
  targetNamespace: monitoring
  values:
    service:
      type: NodePort
      nodePort: 32006
    zabbixServer:
      enabled: true
    zabbixWeb:
      enabled: true
      adminUser: Admin
      adminPassword: zabbix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
