---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zabbix
  namespace: flux-system
spec:
  chart:
    spec:
      chart: zabbix
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: zabbix-community
        namespace: flux-system
  interval: 10m
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: NodePort
      nodePort: 32006
    zabbixServer:
      enabled: true
    zabbixWeb:
      enabled: true
      adminUser: Admin
      adminPassword: zabbix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zabbix-community
  namespace: flux-system
spec:
  url: https://zabbix-community.github.io/helm-zabbix
  interval: 10m