---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.2
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  interval: 10s
  releaseName: sealed-secrets
  targetNamespace: sealed-secrets
  timeout: 1m0s