---
apiVersion: v1
kind: Namespace
metadata:
  name: basier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: block-buster
    version: 7.2.0
    env: dev
  name: demo1
  namespace: basier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: block-buster
  strategy: {}
  template:
    metadata:
      labels:
        app: block-buster
        api: downward
        usage: global
        env: dev
        version: 7.2.0
      annotations:
        vault.hashicorp.com/agent-inject: true
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/db/config'
    spec:
      serviceAccountName: internal-app
      containers:
        - name: app
          image:  siddharth67/block-buster-dev:7.2.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "20m"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: block-buster
  name: demo1-service
  namespace: basier
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    app: block-buster
    version: 7.2.0
    env: dev
  type: NodePort
